name: my-test-site
recipe: laravel
config:
  webroot: ./public
  php: '7.1'
  via: apache
  database: mariadb:10.3
  xdebug: true

proxy:
  appserver:
    - laravel.lndo.site
    
services:
  database:
    portforward: 3307